apiVersion: v1
kind: Service
metadata:
  name: debate-bot
  namespace: debate-bot
  labels:
    app: debate-bot
spec:
  type: ClusterIP
  selector:
    app: debate-bot
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
